### ISSUE TITLE
demo test erro

### ISSUE THREAD

**Issue by moyans** [makefile/frcnn#4]
I0718 10:47:16.587196 12924 net.cpp:256] Network initialization done.
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140258106165888:
  #000: ../../../src/H5F.c line 439 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: ../../../src/H5Fint.c line 554 in H5F_is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: ../../../src/H5FD.c line 993 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: ../../../src/H5FDsec2.c line 339 in H5FD_sec2_open(): unable to open file: name = 'models/FRCNN/VGG16_faster_rcnn_final.caffemodel', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0

**Comment by makefile** [comment]
It's due to the absence of trained caffemodel file. You need specify the file path.

**Comment by moyans** [comment]
thanks
