### ISSUE TITLE
where is test_inference.prototxt? is test.proto ?

### ISSUE THREAD

**Issue by moyans** [makefile/frcnn#6]
when i run `sh examples/FRCNN/res50/test_frcnn.sh 0`  get this erro  
I0719 11:41:09.491593  2885 frcnn_param.cpp:232] iter_test            : -1
F0719 11:41:09.491624  2885 io.cpp:45] Check failed: fd != -1 (-1 vs. -1) File not found: models/FRCNN/res50/test_inference.prototxt
*** Check failure stack trace: ***
    @     0x7f169f8065cd  google::LogMessage::Fail()
    @     0x7f169f808433  google::LogMessage::SendToLog()
    @     0x7f169f80615b  google::LogMessage::Flush()
    @     0x7f169f808e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f169ff0a930  caffe::ReadProtoFromTextFile()
    @     0x7f169ff49516  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f169fe2cd12  caffe::Net<>::Net()
    @     0x7f16a0069dd3  FRCNN_API::Detector::Set_Model()
    @           0x40469d  main
    @     0x7f169e252830  __libc_start_main
    @           0x407089  _start
    @              (nil)  (unknown)
Command terminated by signal 6
0.11user 0.19system 0:00.46elapsed 67%CPU (0avgtext+0avgdata 322720maxresident)k
1768inputs+32outputs (3major+49767minor)pagefaults 0swaps
Called with args:
Namespace(ans_file='examples/FRCNN/results/voc2007_test_res50_2883.frcnn', gt_file='examples/FRCNN/dataset/voc2007.test', overlap=0.5)
Results File(examples/FRCNN/results/voc2007_test_res50_2883.frcnn) does not exist

**Comment by makefile** [comment]
The error message says that it didn't find prototxt file for testing. so you need specify one test prototxt corresponding to the train prototxt.

**Comment by moyans** [comment]
I use the test.proto runing well it. thank you for your answer
